import { z } from "zod";
import { PatchResultSchema } from "../patching/types";

/**
 * A program-declared scope item. Mirrors HackerOne's `structured_scope`
 * resource — when a report is ingested from H1, these come from the
 * program's official scope list and should be treated as authoritative.
 */
export const StructuredScopeAssetSchema = z.object({
  assetIdentifier: z
    .string()
    .describe(
      "Asset value — e.g. '*.example.com', 'com.acme.app', '127.0.0.1/32'",
    ),
  assetType: z
    .string()
    .describe("HackerOne asset type — e.g. 'URL', 'DOMAIN', 'CIDR', 'OTHER'"),
  eligibleForSubmission: z
    .boolean()
    .describe("Whether the program accepts submissions against this asset"),
});
export type StructuredScopeAsset = z.infer<typeof StructuredScopeAssetSchema>;

/**
 * Structured form of an inbound bug bounty report after parsing.
 *
 * Used as the canonical input shape downstream — JSON reports are parsed
 * directly and free-form (markdown / email / text) reports are extracted
 * via an LLM call into this shape.
 */
export const BountyReportSchema = z.object({
  title: z.string().describe("Short title of the reported vulnerability"),
  reporterHandle: z
    .string()
    .optional()
    .describe("Reporter handle / username, if present in the report"),
  claimedSeverity: z
    .enum(["CRITICAL", "HIGH", "MEDIUM", "LOW", "INFORMATIONAL", "UNKNOWN"])
    .describe("Severity as claimed by the reporter (UNKNOWN if not stated)"),
  vulnerabilityClass: z
    .string()
    .describe(
      "Reporter-claimed vulnerability class — e.g., 'Reflected XSS', 'IDOR', 'SSRF'",
    ),
  affectedUrl: z
    .string()
    .describe(
      "Affected URL or endpoint as described in the report. May be a full URL or a path.",
    ),
  affectedComponent: z
    .string()
    .optional()
    .describe("Optional affected component / parameter / feature name"),
  attackerModel: z
    .string()
    .describe(
      "Required attacker capability — e.g. 'unauthenticated', 'authenticated low-priv user', 'admin'",
    ),
  description: z
    .string()
    .describe("Free-form description of the vulnerability as reported"),
  impact: z.string().describe("Claimed impact"),
  pocSteps: z
    .array(z.string())
    .describe("Ordered list of steps the reporter used to reproduce the issue"),
  pocCurl: z
    .string()
    .optional()
    .describe(
      "Optional curl command or raw HTTP request demonstrating the issue",
    ),
  references: z
    .array(z.string())
    .optional()
    .describe("Any CVE / CWE / blog references cited in the report"),
  /**
   * HackerOne report ID, if the report was ingested via webhook or API.
   * Useful for correlating outputs back to the inbox.
   */
  hackerOneReportId: z.string().optional(),
  /**
   * Program-declared structured scopes — only populated when ingested from
   * HackerOne. Treated as authoritative ground truth by `checkScope` when
   * present.
   */
  structuredScopes: z.array(StructuredScopeAssetSchema).optional(),
});

export type BountyReport = z.infer<typeof BountyReportSchema>;

/**
 * Program context loaded from convention-based files in the repo.
 * Each field is independently nullable so missing files are tolerated.
 */
export interface ProgramContext {
  /** `.apex/bug-bounty/scope.md` — what's in/out of scope */
  scope: string | null;
  /** `.apex/bug-bounty/engagement.md` — program rules, excluded vuln classes, etc. */
  engagement: string | null;
  /** `.apex/bug-bounty/business-context.md` — known acceptable risks, criticality */
  businessContext: string | null;
  /** Latest `.apex/threat-models/*.md` — generated by /threat-model */
  threatModel: string | null;
  /** Absolute path of the threat-model file that was loaded, if any */
  threatModelPath: string | null;
}

// ---------------------------------------------------------------------------
// Signal types — each produced by a different orchestration step
// ---------------------------------------------------------------------------

export const ScopeCheckResultSchema = z.object({
  inScope: z.boolean(),
  hostInScope: z.boolean().describe("Whether the host alone passes scope"),
  policyInScope: z
    .boolean()
    .describe(
      "Whether the report passes program policy (scope.md + engagement.md). True when no policy files are present.",
    ),
  hostScopeSource: z
    .enum(["structured-scopes", "session-allowed-hosts", "none"])
    .describe(
      "Which scope source decided the host-level check. 'structured-scopes' = H1 program-declared assets (preferred when present); 'session-allowed-hosts' = operator-supplied session scope; 'none' = no scope enforcement.",
    ),
  reason: z
    .string()
    .describe(
      "Human-readable reason — quote of the failing rule when out of scope, or 'in scope' otherwise.",
    ),
});
export type ScopeCheckResult = z.infer<typeof ScopeCheckResultSchema>;

export const DupCheckResultSchema = z.object({
  duplicate: z.boolean(),
  matchType: z.enum(["exact", "application-wide", "semantic", "none"]),
  matchedTitle: z.string().optional(),
  matchedEndpoint: z.string().optional(),
});
export type DupCheckResult = z.infer<typeof DupCheckResultSchema>;

export const LiveVerificationResultSchema = z.object({
  reproduced: z.boolean(),
  evidence: z
    .string()
    .describe(
      "Concrete evidence of reproduction or non-reproduction — HTTP status codes, response snippets, error messages",
    ),
  observations: z
    .string()
    .describe("Anything else the verifier noticed during the attempt"),
});
export type LiveVerificationResult = z.infer<
  typeof LiveVerificationResultSchema
>;

export const ClaimVerificationStatusSchema = z.enum([
  "verified",
  "contradicted",
  "partial",
  "untested",
]);
export type ClaimVerificationStatus = z.infer<
  typeof ClaimVerificationStatusSchema
>;

export const MaterialClaimSchema = z.object({
  id: z.string().describe("Stable identifier for this material claim"),
  claim: z.string().describe("The concrete report claim being verified"),
  required: z
    .boolean()
    .describe("Whether this claim must be verified before accepting"),
});
export type MaterialClaim = z.infer<typeof MaterialClaimSchema>;

export const ClaimVerificationEntrySchema = MaterialClaimSchema.extend({
  status: ClaimVerificationStatusSchema,
  evidence: z
    .string()
    .describe(
      "Concrete evidence supporting the status, or what was missing/contradicted",
    ),
});
export type ClaimVerificationEntry = z.infer<
  typeof ClaimVerificationEntrySchema
>;

export const ClaimVerificationResultSchema = z.object({
  claims: z.array(ClaimVerificationEntrySchema),
  summary: z.string().describe("Short rollup of the claim verification result"),
});
export type ClaimVerificationResult = z.infer<
  typeof ClaimVerificationResultSchema
>;

export const ThreatModelAlignmentSchema = z.object({
  aligned: z
    .boolean()
    .describe(
      "Whether the reported vulnerability maps onto a documented attack path or asset",
    ),
  mappedThreats: z
    .array(z.string())
    .describe("Threat-model attack path IDs / names this report maps onto"),
  businessAcceptedRisk: z
    .boolean()
    .describe(
      "Whether the threat model or business-context marks this as an accepted risk",
    ),
  notes: z.string(),
});
export type ThreatModelAlignment = z.infer<typeof ThreatModelAlignmentSchema>;

export const CvssSummarySchema = z.object({
  score: z.number(),
  severity: z.string(),
  vectorString: z.string(),
  reasoning: z.string(),
});
export type CvssSummary = z.infer<typeof CvssSummarySchema>;

// ---------------------------------------------------------------------------
// Decision
// ---------------------------------------------------------------------------

export const TriageOutcome = z.enum(["accept", "reject", "needs-info"]);
export type TriageOutcome = z.infer<typeof TriageOutcome>;

export const TriageReason = z.enum([
  "confirmed",
  "out-of-scope",
  "duplicate",
  "unreproducible",
  "informational",
  "business-accepted-risk",
  "missing-info",
]);
export type TriageReason = z.infer<typeof TriageReason>;

/**
 * Canonical HackerOne report state names. Maps onto the state machine
 * documented at https://docs.hackerone.com/en/articles/8475030-report-states.
 *
 * `null` is used for outcomes that do not have a clean H1 state mapping
 * (currently unused — every outcome maps to a state).
 */
export const HackerOneState = z.enum([
  "Triaged",
  "Needs More Info",
  "Duplicate",
  "Informative",
  "Not Applicable",
]);
export type HackerOneState = z.infer<typeof HackerOneState>;

export const TriageDecisionSchema = z.object({
  outcome: TriageOutcome,
  reason: TriageReason,
  rationale: z
    .string()
    .describe("One- to two-sentence explanation grounded in the signals"),
  suggestedHackerOneState: HackerOneState.nullable().describe(
    "Suggested H1 inbox state to transition the report to.",
  ),
  draftReplyMessage: z
    .string()
    .describe(
      "Paste-ready paragraph the engineer can post to the reporter when changing state.",
    ),
});
export type TriageDecision = z.infer<typeof TriageDecisionSchema>;

// ---------------------------------------------------------------------------
// Final emitted result
// ---------------------------------------------------------------------------

export const TriageResultSchema = z.object({
  schemaVersion: z.literal(1),
  reportPath: z.string(),
  target: z.string(),
  generatedAt: z.string().describe("ISO 8601 timestamp"),
  report: BountyReportSchema,
  scope: ScopeCheckResultSchema,
  duplicate: DupCheckResultSchema,
  verification: LiveVerificationResultSchema.nullable(),
  claimVerification: ClaimVerificationResultSchema.nullable(),
  cvss: CvssSummarySchema.nullable(),
  threatModelAlignment: ThreatModelAlignmentSchema.nullable(),
  decision: TriageDecisionSchema,
  remediation: PatchResultSchema.nullable(),
});
export type TriageResult = z.infer<typeof TriageResultSchema>;
