// Auto-generated by scripts/generate-models.ts — do not edit manually.
// Re-generate: bun run generate:models

import type { ModelInfo } from "../ai";

export const ANTHROPIC_MODELS: ModelInfo[] = [
  {
    id: "claude-3-haiku-20240307",
    name: "Claude 3 Haiku (2024-03-07)",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-haiku-4-5-20251001",
    name: "Claude Haiku 4.5 (2025-10-01)",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-haiku-4-5",
    name: "Claude Haiku 4.5",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-opus-4-0",
    name: "Claude Opus 4.0",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-opus-4-20250514",
    name: "Claude Opus 4 (2025-05-14)",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-opus-4-1-20250805",
    name: "Claude Opus 4.1 (2025-08-05)",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-opus-4-1",
    name: "Claude Opus 4.1",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-opus-4-5",
    name: "Claude Opus 4.5",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-opus-4-5-20251101",
    name: "Claude Opus 4.5 (2025-11-01)",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-sonnet-4-0",
    name: "Claude Sonnet 4.0",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-sonnet-4-20250514",
    name: "Claude Sonnet 4 (2025-05-14)",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-sonnet-4-5-20250929",
    name: "Claude Sonnet 4.5 (2025-09-29)",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-sonnet-4-5",
    name: "Claude Sonnet 4.5",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-sonnet-4-6",
    name: "Claude Sonnet 4.6",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-opus-4-6",
    name: "Claude Opus 4.6",
    provider: "anthropic",
    contextLength: 200000,
  },
  {
    id: "claude-opus-4-7",
    name: "Claude Opus 4.7",
    provider: "anthropic",
    contextLength: 1000000,
  },
  {
    id: "claude-opus-4-8",
    name: "Claude Opus 4.8",
    provider: "anthropic",
    contextLength: 1000000,
  },
];
