// Auto-generated by scripts/generate-models.ts — do not edit manually.
// Re-generate: bun run generate:models

import type { ModelInfo } from "../ai";

export const GOOGLE_MODELS: ModelInfo[] = [
  {
    id: "gemini-2.0-flash",
    name: "Gemini 2.0 Flash",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-2.0-flash-001",
    name: "Gemini 2.0 Flash 001",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-2.0-flash-lite",
    name: "Gemini 2.0 Flash Lite",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-2.0-flash-lite-001",
    name: "Gemini 2.0 Flash Lite 001",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-2.5-pro",
    name: "Gemini 2.5 Pro",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-2.5-flash-lite",
    name: "Gemini 2.5 Flash Lite",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-2.5-flash-lite-preview-09-2025",
    name: "Gemini 2.5 Flash Lite Preview 09 2025",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-2.5-computer-use-preview-10-2025",
    name: "Gemini 2.5 Computer Use Preview 10 2025",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-3-pro-preview",
    name: "Gemini 3 Pro Preview",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-3-flash-preview",
    name: "Gemini 3 Flash Preview",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-3.1-pro-preview",
    name: "Gemini 3.1 Pro Preview",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-3.1-pro-preview-customtools",
    name: "Gemini 3.1 Pro Preview Custom Tools",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-3.1-flash-lite-preview",
    name: "Gemini 3.1 Flash Lite Preview",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-pro-latest",
    name: "Gemini pro (Latest)",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-flash-latest",
    name: "Gemini flash (Latest)",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "gemini-flash-lite-latest",
    name: "Gemini flash Lite (Latest)",
    provider: "google",
    contextLength: 1000000,
  },
  {
    id: "nano-banana-pro-preview",
    name: "nano-banana-pro Preview",
    provider: "google",
  },
  {
    id: "aqa",
    name: "aqa",
    provider: "google",
  },
  {
    id: "gemini-robotics-er-1.5-preview",
    name: "Gemini robotics Er 1.5 Preview",
    provider: "google",
  },
  {
    id: "gemma-3-1b-it",
    name: "Gemma 3 1B Instruct",
    provider: "google",
    contextLength: 8192,
  },
  {
    id: "gemma-3-4b-it",
    name: "Gemma 3 4B Instruct",
    provider: "google",
    contextLength: 8192,
  },
  {
    id: "gemma-3n-e4b-it",
    name: "Gemma 3n e4b Instruct",
    provider: "google",
    contextLength: 8192,
  },
  {
    id: "gemma-3n-e2b-it",
    name: "Gemma 3n e2b Instruct",
    provider: "google",
    contextLength: 8192,
  },
  {
    id: "gemma-3-12b-it",
    name: "Gemma 3 12B Instruct",
    provider: "google",
    contextLength: 8192,
  },
  {
    id: "gemma-3-27b-it",
    name: "Gemma 3 27B Instruct",
    provider: "google",
    contextLength: 8192,
  },
];
