import type { z } from "zod";
import type { StreamTextOnStepFinishCallback, ToolSet } from "ai";
import { CodeAgent } from "../codeAgent/agent";
import {
  AppInfoSchema,
  DiscoverySummarySchema,
  WHITEBOX_ENRICHMENT_SYSTEM_PROMPT,
  type DiscoverySummary,
} from "../../../workflows/whiteboxAttackSurface";
import type {
  ConsolidatedEndpoint,
  FrameworkId,
} from "../../../integrations/surface/types";
import type { ClassifiedEndpoint } from "../../../integrations/surface/classifier";
import type { AIModel, CacheMetrics } from "../../../ai";
import type { AIAuthConfig } from "../../../ai/utils";
import type { SessionInfo } from "../../../session";
import type { AgentEventBus } from "../../../eventBus";
import type { AttackSurfaceRegistry } from "../../../findings/attackSurfaceRegistry";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/** Apex-side `App` info — mirrors Phase 1's `AppInfoSchema`. */
export type AppInfo = z.infer<typeof AppInfoSchema>;

/**
 * A consolidated endpoint plus its page-vs-API classification — the unit
 * the enrichment agent reasons over. Structural fields are deterministic
 * (from surface); `classifiedMethod` carries the apex-shape method array
 * (e.g. `["PAGE"]` for renderable pages).
 */
export interface EnrichmentEndpoint extends ConsolidatedEndpoint {
  classifiedMethod: ClassifiedEndpoint["method"];
  isPage: boolean;
}

/**
 * Input for {@link runEnrichmentAgent}. Mirrors the per-task `CodeAgent`
 * spawn shape from `runWhiteboxAttackSurfaceWorkflow` Phase 2, specialized
 * for "endpoint list arrives pre-built; enrich rather than enumerate."
 */
export interface EnrichmentAgentInput {
  codebasePath: string;
  app: AppInfo;
  endpoints: EnrichmentEndpoint[];
  frameworks: FrameworkId[];
  model: AIModel;
  session: SessionInfo;
  authConfig?: AIAuthConfig;
  abortSignal?: AbortSignal;
  eventBus?: AgentEventBus;
  attackSurfaceRegistry?: AttackSurfaceRegistry;
  onStepFinish?: StreamTextOnStepFinishCallback<ToolSet>;
  onCacheMetrics?: (metrics: CacheMetrics) => void;
  projectThreatModel?: string;
}

// ---------------------------------------------------------------------------
// Objective builder
// ---------------------------------------------------------------------------

interface BuildObjectiveOpts {
  app: AppInfo;
  codebasePath: string;
  endpoints: EnrichmentEndpoint[];
  frameworks: FrameworkId[];
}

/**
 * Build the per-app enrichment prompt: deterministic endpoint list +
 * per-endpoint `document_endpoint` asks + non-discovery directive.
 *
 * Pentest objectives are auto-generated by `document_endpoint` (via
 * `generateThreatModelForEndpoint`) — the agent does not pass them.
 * The objective here covers only the structural/descriptive fields
 * the agent actually needs to provide.
 */
export function buildEnrichmentObjective(opts: BuildObjectiveOpts): string {
  const { app, codebasePath, endpoints, frameworks } = opts;

  const frameworkLabel =
    frameworks.length > 0 ? frameworks.join(", ") : "unknown";

  const endpointList = endpoints
    .map((ep, i) => {
      const method = ep.classifiedMethod.join(",");
      const auth = ep.auth.length > 0 ? ep.auth.join(", ") : "none";
      const authPrefill = ep.auth.length > 0;
      const endpointType = ep.isPage ? "web-endpoint" : "api-endpoint";
      return `${i + 1}. **${method} ${ep.path}**
    - file: ${ep.file}:${ep.line}
    - handler: ${ep.handler}
    - endpointType: ${endpointType}
    - auth signals: ${auth}
    - prefilled authRequired: ${authPrefill}`;
    })
    .join("\n\n");

  return `# Enrich Endpoints for ${app.name}

## Codebase
- **Repository root:** ${codebasePath}
- **App location:** ${app.location}
- **Framework(s):** ${frameworkLabel}

## Endpoints (deterministically extracted by surface)

${endpointList}

## Task

For each endpoint above, call \`document_endpoint\` exactly once with these fields (flat, not nested):

- **appName**: \`"${app.name}"\`
- **routePath**: the route path shown above (e.g. \`/api/users/:id\`). The HTTP path a client requests — NOT a source-file path.
- **method**: the method array shown above (e.g. \`["GET","POST"]\`, or \`"PAGE"\` for renderable pages).
- **endpointType**: \`"web-endpoint"\` for entries with method \`PAGE\`, \`"api-endpoint"\` otherwise. Already pre-determined per entry above.
- **file**, **line**, **handler**: as listed above. Do not modify them.
- **authRequired**: start from the prefilled value above. Override only after reading the middleware chain at the indicated file when the signals are genuinely ambiguous.
- **description**: 1-2 sentences explaining what this endpoint does in plain English. Read the handler at \`file:line\` if needed.
- **riskLevel**: one of \`CRITICAL\`, \`HIGH\`, \`MEDIUM\`, or \`LOW\`. CRITICAL for auth/payment/admin or unauthenticated state-changing routes; HIGH for authenticated user-data mutations; MEDIUM for general; LOW for static/public reads.
- **toolCallDescription**: a one-line human-readable description of what this tool call is doing.

You do NOT pass \`pentestObjectives\` — \`document_endpoint\` generates them automatically from the fields above.

**Do NOT re-discover routes — the list above is complete and final.** Do not call \`list_files\` or \`grep\` to look for additional routes. Surface already enumerated them deterministically; any divergence defeats the purpose. You may \`read_file\` at the indicated handler line to ground your description and refine \`authRequired\`, but never to expand the route list.

When finished, call \`response\` with the count of endpoints documented (must equal the number above: ${endpoints.length}).`;
}

// ---------------------------------------------------------------------------
// Agent runner
// ---------------------------------------------------------------------------

/**
 * Spawn a single per-app enrichment {@link CodeAgent} and consume its stream.
 * Mirrors the per-task spawn pattern from `runWhiteboxAttackSurfaceWorkflow`
 * Phase 2: `enrich-${app.name}` subagent id, `document_app` excluded (Phase 1
 * owns apps), same eventBus emit + try/catch shape. Concurrency is the
 * caller's responsibility (`runWithBoundedConcurrency`, `DEFAULT_CONCURRENCY = 5`).
 */
export async function runEnrichmentAgent(
  opts: EnrichmentAgentInput,
): Promise<void> {
  const {
    codebasePath,
    app,
    endpoints,
    frameworks,
    model,
    session,
    authConfig,
    abortSignal,
    eventBus,
    attackSurfaceRegistry,
    onStepFinish,
    onCacheMetrics,
    projectThreatModel,
  } = opts;

  const subagentId = `enrich-${app.name}`;

  eventBus?.emit("subagent-spawn", {
    subagentId,
    name: app.name,
    input: {
      app: app.name,
      type: "enrichment",
      endpointCount: endpoints.length,
    },
  });

  const objective = buildEnrichmentObjective({
    app,
    codebasePath,
    endpoints,
    frameworks,
  });

  const agent = new CodeAgent<DiscoverySummary>({
    codebasePath,
    objective,
    system: WHITEBOX_ENRICHMENT_SYSTEM_PROMPT,
    model,
    session,
    authConfig,
    abortSignal,
    attackSurfaceRegistry,
    eventBus,
    subagentId,
    onStepFinish: (event) => onStepFinish?.(event),
    onCacheMetrics,
    responseSchema: DiscoverySummarySchema,
    excludeTools: ["document_app"],
    projectThreatModel,
  });

  try {
    await agent.consume();
    eventBus?.emit("subagent-complete", {
      subagentId,
      status: "completed",
    });
  } catch (error) {
    console.error(
      `[enrichment-agent] "${subagentId}" FAILED:`,
      error instanceof Error ? error.message : String(error),
    );
    eventBus?.emit("subagent-complete", {
      subagentId,
      status: "failed",
    });
  }
}
