/**
 * Orchestrator Agent Types
 *
 * Types for the LLM-based orchestrator that replaces heuristics-based
 * vulnerability class inference.
 */

import type { AIModel } from '../../ai';
import type { AttackSurfaceAnalysisResults, PentestTarget } from '../attackSurfaceAgent/types';
import type { Session } from '../../session';
import type { VulnerabilityClass } from '../orchestrator/types';

/**
 * Authentication information for a test target
 */
export interface AuthenticationInfo {
  /** Authentication method (e.g., "cookie-based session", "JWT bearer token") */
  method: string;

  /** How to authenticate */
  details: string;

  /** Credentials if available */
  credentials?: string;

  /** Session cookies if available */
  cookies?: string;

  /** Auth headers if available */
  headers?: string;

  /** How auth was discovered */
  discovery?: {
    discoveryMethod: string;
    discoveryExplanation: string;
    confidence: number;
  };
}

/**
 * A single test entry in the test plan
 */
export interface TestPlanEntry {
  /** Target URL/endpoint */
  target: string;

  /** Specific objective for this test */
  objective: string;

  /** Vulnerability class to test for */
  vulnClass: VulnerabilityClass;

  /** Whether authentication is required for this test */
  authNeeded: boolean;

  /** Authentication information if authNeeded is true */
  authInfo?: AuthenticationInfo;

  /** Priority level for this test */
  priority: 'critical' | 'high' | 'medium' | 'low';

  /** Rationale explaining why this vuln class applies to this target */
  rationale: string;
}

/**
 * Complete test plan generated by the orchestrator agent
 */
export interface TestPlan {
  /** All tests to run */
  tests: TestPlanEntry[];

  /** Overall reasoning for the test plan */
  reasoning: string;

  /** Timestamp when plan was created */
  createdAt: string;
}

/**
 * Input for the orchestrator agent
 */
export interface OrchestratorAgentInput {
  /** Results from the attack surface agent */
  attackSurfaceResults: AttackSurfaceAnalysisResults;

  /** Session information */
  session: Session.SessionInfo;

  /** AI model to use */
  model: AIModel;

  /** Optional callback for progress updates */
  onProgress?: (message: string) => void;

  /** Abort signal */
  abortSignal?: AbortSignal;
}

/**
 * Result from the orchestrator agent
 */
export interface OrchestratorAgentResult {
  /** The generated test plan */
  testPlan: TestPlan;

  /** Whether the agent completed successfully */
  success: boolean;

  /** Error message if failed */
  error?: string;
}
