// ---------------------------------------------------------------------------
// Harness
// ---------------------------------------------------------------------------

export type { AgentEventMap } from "../../eventBus";
// ---------------------------------------------------------------------------
// Event Bus
// ---------------------------------------------------------------------------
export { AgentEventBus } from "../../eventBus";
export { OffensiveSecurityAgent } from "./offensiveSecurityAgent";
// ---------------------------------------------------------------------------
// System prompts
// ---------------------------------------------------------------------------
export {
  BASE_SYSTEM_PROMPT,
  type BaseSystemPromptOptions,
  buildBaseSystemPrompt,
  buildProvidedFilesSection,
  buildSessionWorkspaceSection,
} from "./prompt";
export type {
  AskUserQuestion,
  AskUserQuestionAnswer,
  AskUserQuestionsResult,
  BrowserClickResult,
  BrowserConsoleResult,
  BrowserEvaluateResult,
  BrowserFillResult,
  BrowserNavigateResult,
  BrowserScreenshotResult,
  BrowserStorageState,
  BrowserToolMode,
  ReportedError,
  SandboxExecuteOptions,
  SandboxExecutionResult,
  SandboxType,
  ShellExecuteResult,
  ToolContext,
  ToolName,
  UnifiedSandbox,
} from "./tools";
// ---------------------------------------------------------------------------
// Tools — re-exported via the tools barrel.
// ---------------------------------------------------------------------------
export {
  ALL_TOOL_NAMES,
  ASK_USER_QUESTIONS_TOOL_NAME,
  AskUserQuestionSchema,
  addMemory,
  assertCommandInScope,
  assertUrlInScope,
  BROWSER_TOOL_NAMES,
  checkpointState,
  checkSandboxPlaywright,
  completeAuthentication,
  crawlAuthenticated,
  createAllTools,
  createAttackSurfaceReport,
  createBrowserTools,
  createBrowserToolset,
  createEmailToolset,
  createFile,
  createReportErrorTool,
  createResponseTool,
  createSandboxBrowserTools,
  createTask,
  createWorkspaceApp,
  createWorkspaceDomain,
  createWorkspaceEndpoint,
  delegateAuth,
  detectAuthScheme,
  documentApp,
  documentEndpoint,
  documentVulnerability,
  EMAIL_TOOL_NAMES,
  EMAIL_TOOL_NAMES_ACTIVE,
  ensureSandboxBrowser,
  ensureSandboxPlaywright,
  executeCommand,
  extractFallbackStdout,
  extractHostname,
  extractHostsFromCommand,
  extractJsEndpoints,
  FAST_STRIKE_EXCLUDED_TOOL_NAMES,
  getAllowedHosts,
  getApexTmpRoot,
  getMemory,
  getPage,
  grep,
  httpRequest,
  installSandboxPlaywright,
  isHostAllowed,
  listFiles,
  listMemories,
  listTasksTool,
  listWorkspaceApps,
  listWorkspaceDomains,
  listWorkspaceEndpoints,
  PentestReportedError,
  PersistentShell,
  PLAN_MODE_TOOL_NAMES,
  PlaywrightMcpSession,
  parseStorageStateResult,
  probeAuthEndpoints,
  provideComparisonResults,
  REPORT_ERROR_TOOL_NAME,
  RESPONSE_TOOL_NAME,
  ReportErrorReasonSchema,
  readFile,
  readSkill,
  readTempfileCapped,
  runAttackSurface,
  runPentestWorkflow,
  ScopeViolationError,
  SEND_EMAIL_TOOL_NAME,
  SKILL_TOOL_NAMES,
  SMS_LIST_MESSAGES_TOOL_NAME,
  SMS_TOOL_NAMES,
  SMS_TOOL_NAMES_ACTIVE,
  sessionHasSmsPasswordless,
  setHeadlessMode,
  setUserAgent,
  setViewportSize,
  spawnCodingAgent,
  spawnPentestAgent,
  spawnPentestSwarm,
  submitPlan,
  testEndpointVariations,
  transformScriptToFunction,
  updateFile,
  updateTask,
  updateWorkspaceApp,
  updateWorkspaceEndpoint,
  validateDiscovery,
  webSearch,
  writePlan,
} from "./tools";
export type {
  CheckpointInput,
  InitRecord,
  StateCheckpoint,
  StepRecord,
  StepTraceWriterOpts,
  ToolOutputType,
  TraceRecord,
} from "./trace";
// ---------------------------------------------------------------------------
// Trace
// ---------------------------------------------------------------------------
export { StepTraceWriter } from "./trace";
export {
  type AgentMode,
  ApexFindingObject,
  type CommandCancelHandle,
  type CreateAgentInput,
  type Finding,
  type OffensiveSecurityAgentInput,
  type SpecializedAgentInput,
} from "./types";
