// Stable external import path. External consumers depend on this barrel.
// Tracked for migration into the public API in #726 — do not delete or
// restructure until those consumers are moved off the deep import.
export { AuthenticationAgent, runAuthenticationAgent } from "./agent";
export type { AuthenticationAgentInput, AuthenticationResult } from "./agent";
export {
  AUTH_BARRIER_TYPES,
  AUTH_METHODS,
  AUTH_STATUSES,
  AttemptRegistrationInputSchema,
  AuthMethodSchema,
  AuthenticateInputSchema,
  DetectAuthSchemeInputSchema,
  DocumentAuthFlowInputSchema,
  ExportAuthForAgentInputSchema,
  GetAuthStateInputSchema,
  LoadAuthFlowInputSchema,
  ProbeAuthEndpointsInputSchema,
  ProbeRegistrationInputSchema,
  REGISTRATION_BARRIERS,
  ROLE_LEVELS,
  RefreshSessionInputSchema,
  TOKEN_TYPES,
  TokenTypeSchema,
  ValidateSessionInputSchema,
} from "./types";
export type {
  AttemptRegistrationInput,
  AttemptRegistrationResult,
  AuthBarrier,
  AuthBarrierType,
  AuthCredentials,
  AuthDiscoveryEvidence,
  AuthDiscoveryInput,
  AuthDiscoveryResult,
  AuthEndpoint,
  AuthFlowDocumentation,
  AuthFlowHints,
  AuthMethod,
  AuthState,
  AuthStatus,
  AuthToken,
  AuthenticateInput,
  AuthenticateResult,
  AuthenticationSubagentInput,
  AuthenticationSubagentResult,
  BrowserFlowConfig,
  CsrfExtraction,
  DetectAuthSchemeInput,
  DetectAuthSchemeResult,
  DocumentAuthFlowInput,
  DocumentAuthFlowResult,
  ExportAuthForAgentInput,
  ExportAuthForAgentResult,
  ExportedAuthInfo,
  GetAuthStateInput,
  GetAuthStateResult,
  LoadAuthFlowInput,
  LoadAuthFlowResult,
  ProbeAuthEndpointsInput,
  ProbeAuthEndpointsResult,
  ProbeRegistrationInput,
  ProbeRegistrationResult,
  RefreshSessionInput,
  RefreshSessionResult,
  RegistrationBarrier,
  RegistrationInfo,
  RoleLevel,
  TokenExtractionConfig,
  TokenType,
  ValidateSessionInput,
  ValidateSessionResult,
} from "./types";
